[build]
  base = "."
  publish = "website/build"
  command = "npm run build"


[functions]
  directory = "netlify/functions"

[functions."mcp"]
  included_files = ["agents/**"]

[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/mcp"
  status = 200


