[build]
  base = "."
  publish = "website/build"
  command = "npm run build"


[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[functions."mcp"]
  included_files = ["agents/**"]

[[redirects]]
  from = "/.well-known/mcp/health"
  to = "/.netlify/functions/mcp-health"
  status = 200
