[build]
  base = "."
  publish = "website/build"
  command = "npm run build"


[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/mcp"
  status = 200

